"""
Report Formatter - Converts architecture reports to markdown
"""
from src.rag.report_generator import ArchitectureReport, MermaidDiagram


def format_report_as_markdown(report: ArchitectureReport) -> str:
    """
    Format architecture report as markdown

    Args:
        report: ArchitectureReport

    Returns:
        Markdown-formatted string
    """
    md = f"""# Architecture Report: {report.project_name}

---

## Executive Summary

{report.executive_summary}

---

## Architecture Patterns

{_format_list(report.architecture_patterns)}

---

## Architectural Layers

{_format_layers(report.layers)}

---

## Key Components

{_format_components(report.key_components)}

---

## Data Flow

{report.data_flow}

---

## Technology Stack

{_format_list(report.technology_stack)}

---

## Strengths

{_format_list(report.strengths)}

---

## Recommendations

{_format_list(report.recommendations)}

---

*Generated by Java Codebase Analyzer*
"""

    return md


def _format_list(items: list) -> str:
    """Format list as markdown"""
    if not items:
        return "- None identified"
    return "\n".join([f"- {item}" for item in items])


def _format_layers(layers) -> str:
    """Format layers as markdown"""
    if not layers:
        return "No layers identified."

    result = []
    for layer in layers:
        result.append(f"### {layer.name}\n")
        result.append(f"**Responsibilities:** {layer.responsibilities}\n")
        result.append(f"**Components:**")
        for comp in layer.components:
            result.append(f"- {comp}")
        result.append("")

    return "\n".join(result)


def _format_components(components) -> str:
    """Format components as markdown"""
    if not components:
        return "No key components identified."

    result = []
    for comp in components:
        result.append(f"### {comp.name} ({comp.type})\n")
        result.append(f"**Purpose:** {comp.purpose}\n")
        if comp.dependencies:
            result.append(f"**Dependencies:** {', '.join(comp.dependencies)}\n")
        result.append("")

    return "\n".join(result)


def format_diagram_with_report(diagram: MermaidDiagram, report: ArchitectureReport) -> str:
    """
    Format diagram with report context as markdown

    Args:
        diagram: MermaidDiagram
        report: ArchitectureReport

    Returns:
        Markdown with diagram
    """
    md = f"""# {diagram.title}

**Project:** {report.project_name}

**Diagram Type:** {diagram.diagram_type}

## Description

{diagram.description}

## Diagram

```mermaid
{diagram.mermaid_code}
```

---

*Generated by Java Codebase Analyzer*
"""

    return md
